version: '3.9'

services:
  localstack:
    container_name: aws_sqs_playground_localstack
    image: localstack/localstack:3.1
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - DEBUG=0
    volumes:
      - ./localstack-volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
